Repository git-flash/FLASH, pull requests merged in 2021-02, with the labels that each got.

#26 Fixed issue #25
  .idea/FLASH.iml
  .idea/codeStyles/Project.xml
  .idea/jsLibraryMappings.xml
  app/views/application/_error_messages.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
Labels: code-patterns

#58 Issue 53
  app/models/user.rb
  app/views/users/_members.html.erb
Labels: A-Sprint 2, enhancement

#55 Fixed #2
  app/controllers/application_controller.rb
Labels: A-Sprint 1, documentation

#54 Better scopes
  app/controllers/attendance_committee_controller.rb
  app/controllers/attendance_user_controller.rb
  app/models/attendance_log.rb
  app/models/committee.rb
  app/models/event.rb
  app/models/user.rb
  app/views/attendance_committee/show.html.erb
  app/views/attendance_user/index.html.erb
  app/views/attendance_user/show.html.erb
Labels: A-Sprint 1, bug, code-patterns, enhancement, rubo-cop

#66 Added Calendar
  Gemfile
  Gemfile.lock
  app/controllers/events_controller.rb
  app/views/events/index.html.erb
  app/views/simple_calendar/_calendar.html.erb
  app/views/simple_calendar/_month_calendar.html.erb
  app/views/simple_calendar/_week_calendar.html.erb
Labels: enhancement

#41 Bug cole fix attendance committee issues
  app/controllers/attendance_committee_controller.rb
  app/views/attendance_committee/index.html.erb
Labels: A-Sprint 1, code-patterns, documentation, rubo-cop
